### PR TITLE
Flush previous session on login

### PR DESCRIPTION
**Pull request by dmcinnes**
This updates the login endpoint to force any previous sessions attached to the browser to explicitly log out before the new user logs in.

Also does the same for login-external requests.

Ready for review @heroku/api

### CODE REVIEW

**Comment by dmcinnes** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;xTAvwjl7&#x2F;148-pen-test-user-session-cross-over"> Pen Test: User Session Cross-over</a>

**Comment by elight** [comment]
LGTM

**Comment by dmcinnes** [comment]
@elight thanks!

**Comment by paulelliott** [comment]
@dmcinnes was this change driven by the security team? I'd be interested to know the history.

**Comment by dmcinnes** [comment]
@paulelliott yes it was, as a result of pen testing: https://trello.com/c/EPEWhrbr/62-2015-pen-test-user-session-cross-over-api

**Pull request merged**
