### PR TITLE
Resolve double color property & prevent white text

### PR DESCRIPTION
**Pull request by dizzyup**
##### Before:
screen shot on 2016-03-03 at 17_37_36
screen shot on 2016-03-03 at 17_37_44

##### After:
screen shot on 2016-03-03 at 17_38_14

### CODE REVIEW

**Comment by dizzyup** [comment]
@heroku/api You guys mind reviewing this and deploying when you get a chance? Thanks!

**Comment by dmcinnes** [comment]
@dizzyup awesome, thank you! :+1:

**Comment by dmcinnes** [comment]
Just released.

**Comment by dizzyup** [comment]
Cheers Doug!!

**Comment by dmcinnes** [comment]
Hey @dizzyup we ran into a problem, I had to roll it back:
```
Sass::SyntaxError: Undefined variable: "$gray-dark".
  (in /app/assets/stylesheets/purple.scss:24)
```
Is this because we're not on the latest purple?

**Comment by dizzyup** [comment]
Argh, shoot, sorry @dmcinnes - hadn't noticed the variables were set locally, not derived from purple. One minute and I'll add the correct color - sorry for the bad deploy!

**Comment by dmcinnes** [comment]
@dizzyup no worries!

**Pull request merged**
