### PR TITLE
Honeybadger -> Rollbar

### LINKED ISSUE #148: Move to Rollbar
On HoneyBadger currently, don't think the account is still running

### PR DESCRIPTION
**Pull request by dmcinnes**
Identity is still on Honeybadger, this pull converts it to Rollbar.

Fixes #148

### CODE REVIEW

**Comment by brandur** [comment]
OMGGG!!!!!! Thanks Doug! This looks amazing.

Would you mind just doing a quick test of your local installation and just verify that:

1. Unhandled errors are indeed thrown to Rollbar.
2. Internally thrown errors for flow control are not thrown to Rollbar.

I usually do this by adding a Rollbar key locally and creating a dummy endpoint that I can hit that just responds with an exception. It's kind of a safe thing to do because all the monkey patching done in the Rollbar gem tends to make it behave in somewhat non-intuitive ways.

**Comment by dmcinnes** [comment]
OK confirmed it locally after some hair-pulling -- `show_exceptions` defaults to true when you're in development mode, and when enabled Sinatra catches errors before any middleware can see them. :disappointed: 

So it's good to go.
Rollbar Project:
https://rollbar.com/Heroku-3/identity/items/

**Comment by brandur** [comment]
> OK confirmed it locally after some hair-pulling -- show_exceptions defaults to true when you're in development mode, and when enabled Sinatra catches errors before any middleware can see them. :disappointed: 

Fuuuu. Yeah, this implicit `RACK_ENV` behavior is the worst.

Thank-you though! +1 to merge and ship if you want to give it a shot.

**Comment by dmcinnes** [comment]
Cool, will release it today. Thanks!

**Pull request merged**
