### PR TITLE
Tweak login page when user is coming from the authorization flow

### PR DESCRIPTION
**Pull request by pedro**
WIP, looks like this:

screen shot 2015-08-24 at 4 32 46 pm

I'll see if I can get heroku/api#4740 in to make this message more specific with the registered client name. Don't merge for now.

### CODE REVIEW

**Comment by pedro** [comment]
New version: `Parse (test)` is the name of my OAuth client

screen shot 2015-08-27 at 1 42 07 pm

**Comment by pedro** [comment]
@jonmountjoy what do you think of this?

Idea is to render the form above instead of the typical login box for users redirected to authorize a third-party OAuth client.

**Comment by pedro** [comment]
Recorded a video showing the sign-up tweaks here:
https://dl.dropboxusercontent.com/u/602927/parse-signup-flow-demo.mov

**Comment by jonmountjoy** [comment]
Nice!

I wonder if:

* You can use a slightly more comfortable color scheme - those two shades of orange you're using look very similar.  You can see the ones we use on Dev Center here.
* You can change the title to:  "Link accounts and log in"  - I suggest that because ultimately they're also logging in here.  
* You can also add this screen to the /design route in id (only visible when running locally)!

What do you think of that verbiage Pedro?

"Please log in or sign up to link your Heroku account with Parse."

I wonder if people will be afraid to do this because they're not seeing the usual OAuth info screen (which of course will come later).    That is, people must not think that *this* is the linking - it's just the start of the linking.  Does that make sense?

So I wonder if the title should not be "Link accounts and log in" as I suggest, but rather "Log in to link accounts" and text should be "Please log in or sign up.  You will then be presented with an OAuth screen in order to link your account with Parse."

Too much?

Thanks!

**Comment by brandur** [comment]
Great job @pedro! This looks really solid to me.

**Comment by pedro** [comment]
Sweet, thank you! Replies to @jonmountjoy inline:

> You can use a slightly more comfortable color scheme - those two shades of orange you're using look very similar. You can see the ones we use on Dev Center here.

For sure, updated!

> You can change the title to: "Link accounts and log in" - I suggest that because ultimately they're also logging in here.

+1. I also like the "Log in to link accounts" idea.

> You can also add this screen to the /design route in id (only visible when running locally)!

Oh yes, added as `/design/login?client=Parse`, the client name there is just a string to you can play with longer names/etc.

> I wonder if people will be afraid to do this because they're not seeing the usual OAuth info screen (which of course will come later). That is, people must not think that this is the linking - it's just the start of the linking. Does that make sense?
> So I wonder if the title should not be "Link accounts and log in" as I suggest, but rather "Log in to link accounts" and text should be "Please log in or sign up. You will then be presented with an OAuth screen in order to link your account with Parse."

True, looking now people might feel uneasy: "log in to give Parse access? access to what, all my apps?".  Playing a little with your copy suggestions and such I ended up with this, let me know what you think:

screen shot 2015-09-01 at 1 44 06 pm

/cc @ntassone, let me know if you'd like to see any further tweaks here. Or feel free to clone/update of course.

**Comment by jonmountjoy** [comment]
Love your copy change @pedro .  I'd just change it to "the request" instead of "their request" and I think you can :shipit:

**Comment by ntassone** [comment]
@pedro @jonmountjoy css changes look good to go!

**Comment by pedro** [comment]
thanks folks! @brandur ready to go, let me go if I can merge/deploy or go for it!

**Comment by brandur** [comment]
@pedro Ship it man!

**Comment by markpundsack** [comment]
Looks like this leaked in to trusted clients too!

screenshot 2015-09-02 14 38 15

**Comment by dmcinnes** [comment]
@markpundsack oh yeah that was our bad, it's been rolled back.

**Comment by pedro** [comment]
damn. fix in #174

**Pull request merged**
