### PR TITLE
Federated identity support

### PR DESCRIPTION
**Pull request by rwz**
This adds two endpoints to support federated identity workflow.

`/federated/:org_name/saml/init` is an entry point to initiate the SAML dance.
`/federated/:org_name/saml/finalize` is the callback URL that accepts the SAMLResponse and exchanges it to authentication data using separate Federated Identity service (https://github.com/heroku/fido).

Ready for review @heroku/api @heroku/enterprise-experience-team

### CODE REVIEW

**Comment by brandur** [comment]
@rwz @dmcinnes Rocking! Hey, is it possible to get some elaboration on how the whole process works somewhere? I don't see much here or in Fido's README.

This is looking good, but I haven't dived in to any depth yet. This does seem to pull a lot of context about SAML into Identity though, which is something that I'd really like to avoid if at all possible. I'll try to suggest an alternate model (if one is even possible) after I have a better standing of the Identity <-> Fido <-> API interaction.

**Comment by dmcinnes** [comment]
@brandur thanks! I've thrown together a process diagram that should help detail what's going on: https://github.com/heroku/fido/blob/fido-process-docs/docs/fido-process.md

**Comment by dmcinnes** [comment]
Mostly the Identity piece is necessary because all of the other services like Dashboard depend on Identity's access token cookie.

**Comment by dmcinnes** [comment]
Closing this in favor of #163

**Pull request closed without merging**
