### PR TITLE
Update to latest purple styles

### PR DESCRIPTION
**Pull request by almonk**
Minor aesthetic tweaks for updated Purple styles. Could you review pls @dizzyup ? :bow: 

Before
screen shot 2015-04-15 at 9 51 50 am

After
screen shot 2015-04-15 at 9 51 54 am

### CODE REVIEW

**Comment by dizzyup** [comment]
Looks good to me! :+1:

**Comment by almonk** [comment]
@jsimone @paulelliott @ntassone any ideas who owns this repo and who can merge/deploy this :)?

**Comment by paulelliott** [comment]
@almonk it looks like API owns it.

**Comment by geemus** [comment]
Thanks!

**Comment by geemus** [comment]
deployed

**Comment by almonk** [comment]
@geemus thanks :balloon: !

**Pull request merged**
