### PR TITLE
Remove jQuery

### PR DESCRIPTION
**Pull request by dmcinnes**
We're only using it for field label focus removal but these labels have been moved to standard HTML5. Only one of the two fields `#reset_email` exist currently anyway...

### CODE REVIEW

**Comment by dmcinnes** [comment]
@heroku/hit this is in purple territory, am I missing something here, or is this fine to delete?

@heroku/api ready for review.

**Comment by dmcinnes** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;gN4I6jpX&#x2F;147-pen-test-outdated-jquery"> Pen Test: Outdated jQuery</a>

**Comment by paulelliott** [comment]
Despite your file names I don't think those have to do with our purple distribution. LGTM! :+1:

**Comment by dmcinnes** [comment]
@paulelliott thanks!

**Comment by mikehale** [comment]
:+1:

**Comment by mattreduce** [comment]
:tada:

**Pull request merged**
