### PR TITLE
Convert change email confirm to use API's v3 PATCH /users/~

### PR DESCRIPTION
**Pull request by dmcinnes**
First part in an effort to move off of API v2.

Depends on https://github.com/heroku/api/pull/4929

### CODE REVIEW

**Comment by dmcinnes** [comment]
Not sure why it keeps insisting those are violations, it does not fail for me locally now that I've updated the `.rubocop.yml` file to a more sensible default. ¯\(º_o)/¯

**Comment by dmcinnes** [comment]
Ready for review @heroku/api

**Comment by rwz** [comment]
LGTM except I'm not sure about `URI.encode_www_form` vs sending params as JSON in the API call.

Seems like it should be JSON since we're using v3, right?

**Comment by dmcinnes** [comment]
Ah you're right! Lazy copying from me. Fixed.

**Comment by mikehale** [comment]
> Ah you're right! Lazy copying from me. Fixed.

Cool. I was curious about that too. Does that mean the api side of things should be updated to use v3_body_params instead of just params? Actually I can't remember which form it was using now...

**Comment by mikehale** [comment]
> Cool. I was curious about that too. Does that mean the api side of things should be updated to use v3_body_params instead of just params? Actually I can't remember which form it was using now...

Actually it looks like most things are using v3_body_params, with the exception of getting the user id: https://github.com/heroku/api/blob/doug-v3-confirm-email-change/lib/api/endpoints/api_v3/users.rb#L41.

I'm not really sure what the difference between params and v3_body_params are.

**Comment by dmcinnes** [comment]
@mikehale The params should be just fields on the URL like user id in `/users/:user_id` (and I think query params as well) and body params are the key=value pairs in JSON in the post body.

**Comment by mikehale** [comment]
heh, it is right there in the name isn't. /me feels :sheep:ish

**Comment by dmcinnes** [comment]
@mikehale no worries! :grinning:

**Pull request merged**
