### PR TITLE
bump to ruby-2.2.1

### PR DESCRIPTION
**Pull request by geemus**
/cc @brandur

### CODE REVIEW

**Comment by brandur** [comment]
@geemus I think you might need to update the .travis.yml as well, but +1 from me! Ship it.

**Comment by geemus** [comment]
@brandur done, will let tests run again and merge (hopefully). I sort of wish it didn't need changed in 3 places, but not worth messing with presently.

**Comment by brandur** [comment]
> I sort of wish it didn't need changed in 3 places, but not worth messing with presently.

Hah, agreed. I always forget one of them. Travis may be able to detect based on a `Gemfile` these days. I'll have to try that one out sometime.

**Comment by geemus** [comment]
merged

**Pull request merged**
