### PR TITLE
SSO Login

### PR DESCRIPTION
**Pull request by naaman**
SSO login adds a small link to initiate single sign-on from the primary login page. It uses the SSO base URL config and appends `/login` to redirect users to the SSO login page.

/cc @dmcinnes

### CODE REVIEW

**Comment by dmcinnes** [comment]
:+1: Fine by me, though who approves the design change? @itchymutt would that be you?

**Comment by naaman** [comment]
Oops, yes that's @itchymutt.

**Comment by naaman** [comment]
Screenshot:

sso link on login

**Comment by itchymutt** [comment]
@naaman The text links are blurring together, can we create more space between them? A suggestion to correct that would be to justify them the same way Salesforce does on their login screen (though adding more space is also fine with me):

screenshot 2015-12-10 12 46 56

Second, copy change "SSO" to "Log in via SSO".

**Comment by naaman** [comment]
Updated screenshot:

sso on login

**Comment by itchymutt** [comment]
@naaman @dmcinnes This gets a +1 from me now!

**Comment by dmcinnes** [comment]
Thanks!

**Pull request merged**
