### PR TITLE
add docker bits

### PR DESCRIPTION
**Pull request by geemus**
note, will need ruby bump to 2.2.3 when #168 comes in

### CODE REVIEW

**Comment by geemus** [comment]
rebased/bumped to 2.2.3

**Comment by brandur** [comment]
Bumped to Ruby 2.2.3 following the merge of #168.

**Comment by brandur** [comment]
Ack, hahahaha

**Comment by brandur** [comment]
@geemus Thank-you! This is sweeeeeeeeeet.

Re-organized your README a bit in cec3ecd. Pulling this in.

**Pull request merged**
