### PR TITLE
Add meta descriptions for login and reset password pages

### PR DESCRIPTION
**Pull request by raul**
This should improve SEO for identity and, more importantly, signup.h.c

### CODE REVIEW

**Comment by dmcinnes** [comment]
Thanks!

**Comment by jonmountjoy** [comment]
Lo @dmcinnes - any idea when this will be deployed?  Thanks!

**Comment by dmcinnes** [comment]
@jonmountjoy thanks for reminding me! I've just deployed it.

**Comment by jonmountjoy** [comment]
\o/ Cheers!

**Pull request merged**
