### PR TITLE
Handle generic client errors for password resets

### LINKED ISSUE #188: Password reset finalize API call doesn't handle rate limit 429 responses
And likely other endpoints as well.

### PR DESCRIPTION
**Pull request by dmcinnes**
Fixes #188

Also updates not found pages for password resets and email confirmations to correctly return a 404 status.

### CODE REVIEW

**Comment by dmcinnes** [comment]
Ready for review @heroku/api

**Comment by rwz** [comment]
LGTM

Also, Hound is amazing

**Comment by rwz** [comment]
I want hound for API badly

**Comment by dmcinnes** [comment]
@rwz +1! As long as we get the .rubocop.yml right it would be super nice

**Pull request merged**
